// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjnbrngonzubxargfnsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqbmJybmdvbnp1YnhhcmdmbnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTkxNTUsImV4cCI6MjA2NDM3NTE1NX0.FJW5W3fiJfx44M5HM56TFnjln7MY9Q9T_eb1sTTDkDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);